# /*---------------------------------------------------------------------------8
# |                                                                            |
# |             SAP: Register BOM                                              |
# |         SAP SCS: deploy SCS Parameter file install template                |
# |         SAP SCS: Install                                                   |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

---
- name:                                "ERS Install: Set BOM facts"
  ansible.builtin.set_fact:
    sap_inifile:                       "{{ bom_base_name }}-ers-{{ ansible_hostname }}.params"
    sap_inifile_template:              "{{ bom_base_name }}-ers-inifile-param.j2"


# Returns bom object
- name:                                "ERS Install: Include 3.3.1-bom-utility role"
  ansible.builtin.include_role:
    name:                              roles-sap/3.3.1-bom-utility
    tasks_from:                        bom-register
  vars:
    bom_name:                          "{{ bom_base_name }}"

- name:                                "ERS Install: Include roles-sap/3.3.1-bom-utility role"
  ansible.builtin.include_role:
    name:                              roles-sap/3.3.1-bom-utility
    tasks_from:                        bom-template
  vars:
    sap_cd_package_cd1:
    sap_cd_package_cd2:
    sap_cd_package_cd3:
    sap_cd_package_cd4:
    sap_cd_package_cd5:
    sap_cd_package_hdbclient:
    sap_ciInstanceNumber:
    app_instance_number:
    sap_ciDialogWPNumber:
    sap_ciBtcWPNumber:
    sap_installSAPHostAgent:
    sap_profile_dir:
    sap_scs_hostname:                  "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_ERS') | first }}"
    sap_db_hostname:
    sap_ciVirtualHostname:
    sap_appVirtualHostname:
  tags:
    - skip_ansible_lint

- name:                                "ERS Install: Create run flag directory"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation
    state:                             directory
    mode:                              0755

- name:                                "ERS Install: reset"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation/sap_deployment_ers.txt
    state:                             absent
  when:                                reinstall

- name:     "Create run flag directory"
  ansible.builtin.file:
    path:   /etc/sap_deployment_automation
    state:  directory
    mode:   0755

- name:               "SAP ERS reset"
  ansible.builtin.file: 
    path: /etc/sap_deployment_automation/sap_deployment_ers.txt
    state: absent
  when: reinstall == true 

- name:     "Create run flag directory"
  ansible.builtin.file:
    path:   /etc/sap_deployment_automation
    state:  directory
    mode:   0755

- name:               "SAP ERS reset"
  ansible.builtin.file: 
    path: /etc/sap_deployment_automation/sap_deployment_ers.txt
    state: absent
  when: reinstall == true 

- name: SAP ERS install variables
  debug:
    msg: "{{ sap_inifile }}"
    verbosity: 2

- name: SAP ERS install variables
  debug:
    msg: "{{ bom.product_ids.ers }}"
    verbosity: 2



# *====================================4=======================================8
#   SAP ERS: Install
# 2230669 - System Provisioning Using a Parameter Input File
#
- name:                                "ERS Install: SAP ERS Install"
  ansible.builtin.shell: |
                                       set -o errexit
                                       set -o pipefail
                                       export TMPDIR=/usr/sap/install
                                       ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/install/downloads/{{ sap_inifile }}     \
                                                 SAPINST_EXECUTE_PRODUCT_ID={{ bom.product_ids.ers }}                          \
                                                 SAPINST_SKIP_DIALOGS=true                                                     \
                                                 SAPINST_START_GUISERVER=false                                                 \
                                                 SAPINST_USE_HOSTNAME={{ ers_virtual_hostname }}
                                       touch /etc/sap_deployment_automation/sap_deployment_ers.txt
  args:
    chdir:                             /usr/sap/install/SWPM
    creates:                           /etc/sap_deployment_automation/sap_deployment_ers.txt
  tags:
    - skip_ansible_lint
  # Skip when TRUE (test mode)
  # when: not test_new_bom
# *====================================4=======================================8

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
